export const POSTS_FETCHED_REQUESTED = 'POSTS_FETCHED_REQUESTED';
export const MY_POSTS_FETCHED_REQUESTED = 'MY_POSTS_FETCHED_REQUESTED';
export const POSTS_FETCHED_FAILED = 'POSTS_FETCHED_FAILED';
export const POSTS_FETCHED_SUCCESSED = 'POSTS_FETCHED_SUCCESSED';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_VIA_GOOGLE_REQUESTED = 'LOGIN_VIA_GOOGLE_REQUESTED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESSED = 'LOGIN_SUCCESSED';
export const REGISTER_REQUESTED = 'REGISTER_REQUESTED';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const REGISTER_SUCCESSED = 'REGISTER_SUCCESSED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const TOKEN_SENDED = 'TOKEN_SENDED';
export const TOKEN_SUCCESSED = 'TOKEN_SUCCESSED';
export const TOKEN_FAILED = 'TOKEN_FAILED';
export const CHANGES_SUCCESSED = 'CHANGES_SUCCESSED';
export const CHANGES_FAILED = 'CHANGES_FAILED';
export const CHANGES_REQUESTED = 'CHANGES_REQUESTED';
export const RESET_MODAL = 'RESET_MODAL';
export const POST_CREATE_REQUESTED = 'POST_CREATE_REQUESTED';
export const POST_CREATE_SUCCESSED = 'POST_CREATE_SUCCESSED';
export const POST_CREATE_FAILED = 'POST_CREATE_FAILED';
export const POST_CHANGE_REQUESTED = 'POST_CHANGE_REQUESTED';
export const POST_CHANGE_SUCCESSED = 'POST_CHANGE_SUCCESSED';
export const POST_CHANGE_FAILED = 'POST_CHANGE_FAILED';
export const FILTER_POSTS = 'FILTER_POSTS';
export const MAX_POSTS_ON_PAGE = 6;
export const categories = [
  'all',
  'title',
  'text',
  'username',
  'tags',
];
